-- ============================================================
-- CAFÉ ARTESANAL — ESQUEMA DO BANCO DE DADOS SUPABASE (PostgreSQL)
-- Disciplina: Segurança em Sistemas da Informação — FICR
-- ============================================================
--
-- Como executar no Supabase:
-- 1. Acesse https://supabase.com e entre no painel do seu projeto
-- 2. No menu lateral esquerdo, clique em "SQL Editor"
-- 3. Cole este script e clique no botão verde "Run" (Executar)
--
-- Princípios de Segurança Aplicados:
-- 1. Defesa em Profundidade: Tipagem estrita e CHECK constraints no banco (tamanho, formato, valores positivos)
-- 2. Row Level Security (RLS): Controle granular de autorização em nível de linha
-- 3. Hashing de Senhas: Senhas armazenadas exclusivamente em hash bcrypt (nunca em texto puro)
-- 4. Trilha de Auditoria Forense: Registro de eventos de segurança, acessos e operações (logs_auditoria)
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABELA DE PESSOAS (Clientes e Funcionários)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pessoas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    "dataCadastro" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_pessoas_nome_len CHECK (char_length(nome) <= 80),
    CONSTRAINT chk_pessoas_cpf_len CHECK (char_length(cpf) <= 14),
    CONSTRAINT chk_pessoas_email_len CHECK (char_length(email) <= 100),
    CONSTRAINT chk_pessoas_telefone_len CHECK (char_length(telefone) <= 15)
);

-- ------------------------------------------------------------
-- 2. TABELA DE PRODUTOS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    sku VARCHAR(20) NOT NULL UNIQUE,
    estoque INTEGER NOT NULL,
    descricao VARCHAR(250),
    "dataCadastro" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_produtos_preco_positivo CHECK (preco > 0),
    CONSTRAINT chk_produtos_estoque_positivo CHECK (estoque >= 0),
    CONSTRAINT chk_produtos_nome_len CHECK (char_length(nome) <= 70),
    CONSTRAINT chk_produtos_sku_len CHECK (char_length(sku) <= 20),
    CONSTRAINT chk_produtos_desc_len CHECK (descricao IS NULL OR char_length(descricao) <= 250)
);

-- ------------------------------------------------------------
-- 3. TABELA DE USUÁRIOS (Autenticação e Controle de Acesso - RBAC)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'operador',
    nome VARCHAR(100) NOT NULL,
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_usuarios_username_len CHECK (char_length(username) <= 50),
    CONSTRAINT chk_usuarios_nome_len CHECK (char_length(nome) <= 100)
);

-- ------------------------------------------------------------
-- 4. TABELA DE LOGS DE AUDITORIA (Trilha Forense de Segurança)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel VARCHAR(20) NOT NULL,
    mensagem TEXT NOT NULL,
    detalhes JSONB,
    ip VARCHAR(45),
    operador VARCHAR(50),
    data_hora TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 5. POLÍTICAS DE SEGURANÇA: ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------
ALTER TABLE pessoas ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_auditoria ENABLE ROW LEVEL SECURITY;

-- Políticas PESSOAS
DROP POLICY IF EXISTS "Permitir leitura pública de pessoas" ON pessoas;
CREATE POLICY "Permitir leitura pública de pessoas" ON pessoas FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir inserção de pessoas" ON pessoas;
CREATE POLICY "Permitir inserção de pessoas" ON pessoas FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir deleção de pessoas" ON pessoas;
CREATE POLICY "Permitir deleção de pessoas" ON pessoas FOR DELETE USING (true);

-- Políticas PRODUTOS
DROP POLICY IF EXISTS "Permitir leitura pública de produtos" ON produtos;
CREATE POLICY "Permitir leitura pública de produtos" ON produtos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir inserção de produtos" ON produtos;
CREATE POLICY "Permitir inserção de produtos" ON produtos FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir deleção de produtos" ON produtos;
CREATE POLICY "Permitir deleção de produtos" ON produtos FOR DELETE USING (true);

-- Políticas USUARIOS (Leitura para autenticação e gestão)
DROP POLICY IF EXISTS "Permitir leitura de usuarios" ON usuarios;
CREATE POLICY "Permitir leitura de usuarios" ON usuarios FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir inserção de usuarios" ON usuarios;
CREATE POLICY "Permitir inserção de usuarios" ON usuarios FOR INSERT WITH CHECK (true);

-- Políticas LOGS_AUDITORIA (Inserção e leitura pela API)
DROP POLICY IF EXISTS "Permitir inserção de logs" ON logs_auditoria;
CREATE POLICY "Permitir inserção de logs" ON logs_auditoria FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir leitura de logs" ON logs_auditoria;
CREATE POLICY "Permitir leitura de logs" ON logs_auditoria FOR SELECT USING (true);

-- ------------------------------------------------------------
-- 6. DADOS DE SEED (Carga Inicial para Demonstração)
-- ------------------------------------------------------------

-- Seed de Pessoas
INSERT INTO pessoas (nome, cpf, email, telefone, tipo)
SELECT 'Ana Beatriz Souza', '123.456.789-00', 'ana.souza@email.com', '(81) 98765-4321', 'Cliente VIP'
WHERE NOT EXISTS (SELECT 1 FROM pessoas WHERE cpf = '123.456.789-00');

INSERT INTO pessoas (nome, cpf, email, telefone, tipo)
SELECT 'Carlos Eduardo Silva', '987.654.321-11', 'carlos.barista@cafearoma.com.br', '(81) 99123-8899', 'Barista (Funcionário)'
WHERE NOT EXISTS (SELECT 1 FROM pessoas WHERE cpf = '987.654.321-11');

-- Seed de Produtos
INSERT INTO produtos (nome, categoria, preco, sku, estoque, descricao)
SELECT 'Espresso Gourmet Arábica 250g', 'Grãos & Pós', 34.90, 'CAF-ESP-250', 45, 'Grãos selecionados 100% Arábica com notas de chocolate amargo e avelã.'
WHERE NOT EXISTS (SELECT 1 FROM produtos WHERE sku = 'CAF-ESP-250');

INSERT INTO produtos (nome, categoria, preco, sku, estoque, descricao)
SELECT 'Cappuccino Italiano Clássico', 'Bebidas Quentes', 16.50, 'BEB-CAP-ITA', 100, 'Espresso duplo, leite vaporizado e espuma cremosa com toque de canela.'
WHERE NOT EXISTS (SELECT 1 FROM produtos WHERE sku = 'BEB-CAP-ITA');

INSERT INTO produtos (nome, categoria, preco, sku, estoque, descricao)
SELECT 'Croissant de Amêndoas', 'Lanches & Sobremesas', 18.00, 'LAN-CRO-AME', 20, 'Massa folhada artesanal recheada e coberta com lâminas de amêndoas tostadas.'
WHERE NOT EXISTS (SELECT 1 FROM produtos WHERE sku = 'LAN-CRO-AME');

-- Seed de Usuários (Hashes bcrypt das senhas 'cafe@2025' e 'espresso123')
INSERT INTO usuarios (username, password_hash, role, nome)
SELECT 'admin', '$2b$10$aQXpxtlzIQ0eQRB.JEZJOe0JcOF/VZXeieG6yyvrtuIvuni7aajly', 'administrador', 'Administrador do Sistema'
WHERE NOT EXISTS (SELECT 1 FROM usuarios WHERE username = 'admin');

INSERT INTO usuarios (username, password_hash, role, nome)
SELECT 'gerente', '$2b$10$cV1CO5x6MmWE7EXJKdyc7uvdvEqnRgkcdk7NCvDVJTmUlrm0LATuq', 'gerente', 'Gerente da Cafeteria'
WHERE NOT EXISTS (SELECT 1 FROM usuarios WHERE username = 'gerente');

-- Seed inicial de auditoria
INSERT INTO logs_auditoria (nivel, mensagem, detalhes, ip, operador)
VALUES ('INFO', 'Banco de dados configurado com sucesso (Esquema de Segurança Completo)', '{"origem": "setup_schema"}'::jsonb, '127.0.0.1', 'sistema');
